version: '3.0'
services:
  db_test:
    image: postgres:16.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5434:5432"
    networks:
      - my_network

  api:
    build: .
    depends_on:
      - db_test
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
             
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
